- functional_testing/Grid_API_Testing/api_testing/testcases/__init__.py
- functional_testing/Grid_API_Testing/api_testing/testcases/testcases_base.py
https://github.com/gig-projects/org_quality/issues/645
> Fix get nodes info method

- functional_testing/Grid_API_Testing/api_testing/testcases/extend_tests/test01_containers_apis.py
Reverts 0-complexity/G8_testing#194
> Revert "Container gateway"

- functional_testing/Openvcloud/ovc_master_hosted/OVC/b_extended/cloudspace_tests.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/b_extended/machine_tests.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/c_advanced/machine_tests.py
- functional_testing/Openvcloud/utils/utils.py
fixes https://github.com/gig-projects/org_quality/issues/738
> create vm with not allowed size test

- functional_testing/Openvcloud/config.ini
- functional_testing/Openvcloud/ovc_master_hosted/OVC/a_basic/users_tests.py
- functional_testing/Openvcloud/utils/utils.py
test001_authenticate_user
test002_get_user_info
test003_check_matching_users
test004_password_reset
test005_create_users_with_same_specs
https://github.com/gig-projects/org_quality/issues/732
>  testcases for users Apis

- functional_testing/Openvcloud/ovc_master_hosted/OVC/c_advanced/machine_tests.py
- functional_testing/Openvcloud/utils/utils.py
fixes https://github.com/gig-projects/org_quality/issues/724
> Test case for checking network data integrity through VMS

- functional_testing/Openvcloud/ovc_master_hosted/OVC/c_advanced/machine_tests.py
- functional_testing/Openvcloud/utils/utils.py
fixes https://github.com/0-complexity/G8_testing/issues/247
> test machine networking

- functional_testing/Openvcloud/ovc_master_hosted/OVC/b_extended/machine_tests.py
fixes https://github.com/0-complexity/G8_testing/issues/253
> testcase for resizing disk

- functional_testing/Openvcloud/ovc_master_hosted/OVC/a_basic/machine_tests.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/a_basic/users_tests.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/b_extended/cloudspace_tests.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/b_extended/machine_tests.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/c_advanced/machine_tests.py
> change "try & except" to "with" form

- .travis.yml
- functional_testing/Openvcloud/ovc_master_hosted/Portal/travis_portal_script.sh
- functional_testing/Openvcloud/tools/travis_script.sh
last portal job
https://travis-ci.org/0-complexity/G8_testing/jobs/311262340
> Travis portal job

- functional_testing/Openvcloud/ovc_master_hosted/ACL/a_basic_operations/acl_cloudspace_test.py
- functional_testing/Openvcloud/ovc_master_hosted/ACL/a_basic_operations/acl_machine_test.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/a_basic/users_tests.py
```
root@ctrl-du-conv-2:/tmp/G8_testing/functional_testing/Openvcloud# nosetests -s -v ovc_master_hosted/OVC/a_basic/users_tests.py:UsersBasicTests.test002_get_user_info --tc-file config.ini --tc=main.environment:du-conv-2
OVC-032 ... ok
----------------------------------------------------------------------
Ran 1 test in 2.652s
OK
root@ctrl-du-conv-2:/tmp/G8_testing/functional_testing/Openvcloud# nosetests -s -v ovc_master_hosted/ACL/a_basic_operations/acl_machine_test.py:Read.test004_machine_getConsoleUrl_listSnapshots_getHistory --tc-file config.ini --tc=main.environment:du-conv-2
ACL-53 ... ok
----------------------------------------------------------------------
Ran 1 test in 81.380s
OK
root@ctrl-du-conv-2:/tmp/G8_testing/functional_testing/Openvcloud# nosetests -s -v …
```
> fix skipped testcases

- functional_testing/Openvcloud/ovc_master_hosted/OVC/b_extended/cloudspace_tests.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/c_advanced/machine_tests.py
- functional_testing/Openvcloud/utils/utils.py
> modifiy wait for machine ip method

- functional_testing/Openvcloud/utils/acl_try_operations.py
> cover getConsumedCloudUnitsByType api

- functional_testing/Openvcloud/ovc_master_hosted/README.md
- functional_testing/Openvcloud/tools/travis_script.sh
> travis docs

- functional_testing/Openvcloud/ovc_master_hosted/OVC/c_advanced/maintenance_tests.py
- functional_testing/Openvcloud/ovc_master_hosted/OVC/d_long_tests/machine_tests.py
fixes: https://github.com/0-complexity/G8_testing/issues/313
fixes: https://github.com/0-complexity/G8_testing/issues/314
> check vm migration in which it is attached to ext. network

- functional_testing/Openvcloud/ovc_master_hosted/OVC/b_extended/cloudspace_tests.py
> check the vfw status of disabled/enabled cloudspaces

- functional_testing/Openvcloud/ovc_master_hosted/OVC/c_advanced/maintenance_tests.py
fixes: https://github.com/0-complexity/G8_testing/issues/319
fixes: https://github.com/0-complexity/G8_testing/issues/320
fixes: https://github.com/0-complexity/G8_testing/issues/321
fixes: https://github.com/0-complexity/G8_testing/issues/315
> Vfw node maintenance

- functional_testing/Openvcloud/RESTful/framework/api/client.py
- functional_testing/Openvcloud/RESTful/framework/api/cloudapi/disks.py
- functional_testing/Openvcloud/RESTful/testcases/cloudapi/test01_disks.py
- functional_testing/Openvcloud/RESTful/testcases/testcase_base.py
fixes https://github.com/0-complexity/G8_testing/issues/363
> add disks acl tests

- functional_testing/Openvcloud/RESTful/framework/api/system/agentcontroller.py
- functional_testing/Openvcloud/RESTful/testcases/system/test02_agentcontroller.py
https://github.com/0-complexity/G8_testing/issues/369
> Swap consume

- performance_testing/scripts/run_fio.py
Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>
> Adds user can specify which cloudspaces to run_fio work on

- performance_testing/Testsuite/1_fio_vms/collect_results.py
- performance_testing/Testsuite/1_fio_vms/demo_create_vms.py
- performance_testing/Testsuite/1_fio_vms/demo_run_fio.py
- performance_testing/scripts/add_vms.py
- performance_testing/scripts/cleanup_vms.py
- performance_testing/scripts/libtest.py
- performance_testing/scripts/run_fio.py
- performance_testing/scripts/run_pgbench.py
- performance_testing/scripts/run_unixbench.py
- performance_testing/scripts/start_vms.py
- performance_testing/scripts/stop_vms.py
Signed-off-by: Ashraf Fouda <ashraf.m.fouda@gmail.com>
> Adds migrate perf test to js9

- .travis.yml
- functional_testing/Openvcloud/ovc_master_hosted/Portal/framework/workflow/login.py
- functional_testing/Openvcloud/ovc_master_hosted/Portal/travis_portal_script.sh
- functional_testing/Openvcloud/tools/travis_script.sh
- solves the problem of travis and zerotier
> Travis fix
